config/routes.rb
Rails.application.routes.draw do
  resources :categories #, only: [:create, :show, :edit, :destroy]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :posts
  resources :contacts, only: [:new, :create]
  resources :galleries

  resources :tasks do
    member do
      put :change
    end
  end

  root "pages#home"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true

  auto_html_for :content do
    html_escape
    image
    youtube(width: "100%", height: 250, auto_play: false)
    link target: "_blank", rel: "nofollow"
    simple_format
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy, :change]

  def index
    @to_do = current_user.tasks.where(state: "to_do")
    @doing = current_user.tasks.where(state: "doing")
    @done = current_user.tasks.where(state: "done")
  end

  def show
  end
  
  def new
    @task = Task.new
  end
  
  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      flash[:success] = "Task was successfully created"
      redirect_to tasks_path
    else
      flash[:danger] = "Unable to save Task!"
      render 'new'
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = "Task was successfully updated"
      redirect_to tasks_path
    else
      flash[:danger] = "Unable to update Task!"
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task was destroyed"
    redirect_to tasks_path
  end

  def change
    @task.update_attributes(state: params[:state])
    flash[:success] = "Task State was updated"
    redirect_to tasks_path
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:content, :state)
    end
end

app/views/tasks/_form.html.erb
<%= render 'shared/errors', obj: @task, message: 'prohibited this task from being saved:' %>
<div class="row">
  <div class="col col-md-6 col-md-offset-3">
    <%= form_for(@task, html: { class: 'form-horizontal', role: 'form' }) do |f| %>
      <div class="form-group">
        <%= f.text_area :content, require: true, autofocus: true,  label: false, placeholder: "Content", html: { class: "form-control" } %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
        <%= link_to 'Cancel', tasks_path, class: 'btn btn-warning' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    created <%= time_ago_in_words(task.created_at) %> ago
    <div class="pull-right">
      <%= link_to "<i class='fa fa-pencil' aria-hidden='true'></i>".html_safe, edit_task_path(task) %>
      <%= link_to "<i class='fa fa-trash' aria-hidden='true'></i>".html_safe, task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  </div>
  <div class="panel-body"><%= raw(task.content_html) %></div>
  <div class="panel-footer text-center">
    <% if task.state == "doing" %>
      <div class="btn-group btn-group-justified">
        <%= link_to "<i class='fa fa-angle-double-left'></i> To Do".html_safe, change_task_path(task, state: "to_do"), method: :put, class: "btn btn-sm btn-block btn-info" %>
        <%= link_to "Done <i class='fa fa-angle-double-right'></i>".html_safe, change_task_path(task, state: "done"), method: :put, class: "btn btn-sm btn-block btn-info" %>
      </div>
    <% elsif task.state == "done" %>
      <%= link_to "<i class='fa fa-angle-double-left'></i> Doing".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-sm btn-block btn-info" %>
    <% else %>
      <%= link_to "Doing <i class='fa fa-angle-double-right'></i>".html_safe, change_task_path(task, state: "doing"), method: :put, class: "btn btn-sm btn-block btn-info" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Task</h1>

  <%= render 'form' %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
  <div class="row">
    <div class="col-md-4">
      <h1 class="text-center">To Do</h1>
      <%= render @to_do %>
    </div>
    <div class="col-md-4">
      <h1 class="text-center">Doing</h1>
      <%= render @doing %>
    </div>
    <div class="col-md-4">
      <h1 class="text-center">Done</h1>
      <%= render @done %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1 class="text-center">New Task</h1>

  <%= render 'form' %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-9">
    <p>
      <strong>Content:</strong>
      <%= @task.content %>
    </p>

    <p>
      <strong>State:</strong>
      <%= @task.state %>
    </p>

    <%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-success' %> |
    <%= link_to 'Back', tasks_path %>
    </div>
  </div>
</div>