config/routes.rb
Rails.application.routes.draw do
  resources :categories #, only: [:create, :show, :edit, :destroy]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :posts
  resources :contacts, only: [:new, :create]
  resources :galleries

  resources :tasks do
    member do
      put :change
    end
  end

  root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_categories
  has_many :categories, through: :post_categories
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 3, maximum: 144 }
  validates :content, presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if current_user
      @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
    else
      @posts = Post.all.where(publish: true).order("created_at desc").paginate(page: params[:page], per_page: 10)
    end
    @categories = Category.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = "Article was successfully created"
      redirect_to @post
    else
      flash[:danger] = "Unable to save Article!"
      render 'new'
    end
  end

  def show
    @categories = Category.all
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Article was successfully updated!"
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Article was successfully deleted!"
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :slug, :user_id, :description, :publish, :image_url, category_ids: [])
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
this.page.url = PAGE_URL;  '<%= url_for([@post, {only_path: false}]) %>';
this.page.identifier = '<%= @post.id %>'; 
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://garciajames.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post, message: 'prohibited this article from being saved:' %>

<div class="row">
  <div class="col col-xs-12">
    <%= form_for(@post, html: { class: 'form-horizontal', role: 'form' }) do |f| %>
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-1">
          <%= f.label "Publish" %>
          <%= f.check_box :publish, class: "cbox" %>
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title of post', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-1">
          <%= f.text_field :image_url, class: 'form-control', placeholder: 'Add Image URL' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-1">
          <%= f.text_area :content, rows: 10, class: 'form-control', placeholder: 'Body of Post' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-1">
          <%= f.text_field :description, class: 'form-control', placeholder: 'Short Description of Post' %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-offset-2 col-sm-8">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "cbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
          <%= f.submit class: 'btn btn-primary' %>
          <%= link_to 'Cancel', posts_path, class: 'btn btn-warning' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<% obj.each do |post| %>
  <h3><%= link_to post.title, post %></h3>
  <% if current_user %>
    <% if post.publish %>
      <span class="label label-success">PUBLISHED</span>
    <% else %>
      <span class="label label-warning">DRAFT</span>
    <% end %>
  <% end %>
  <p><small>Created: <%= time_ago_in_words(post.created_at) %> ago,
    last updated: <%= time_ago_in_words(post.updated_at) %> ago</small></p>
  <p><%= post.description %></p>
  <% if post.categories.any? %>
    <p>Categories: <%= render post.categories %></p>
  <% end %>
  <hr/>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1 class="text-center">All Blog Post</h1>
  <div class="row">
    <div class="col-sm-9">
      <div class="text-center"><%= will_paginate %></div>
        <%= render 'post', obj: @posts %>
      <div class="text-center"><%= will_paginate %></div>
    </div>
    <div class="col-sm-3">
      <%= render 'categories/categories', obj: @categories %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-center">New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-1">
      <% if @post.image_url %>
        <%= image_tag @post.image_url, class: "img-responsive post-image" %>
      <% end %>
      <div class="text-center">
      <h1><%= @post.title %></h1>
        <p><strong>by: <%= @post.user.name %></strong></p>
        <p><small>Updated: <%= @post.updated_at.strftime("%b %d, %Y") %></small></p>
      </div>
      <div class="post-content">
        <%= markdown(@post.content) %>
        <% if @post.categories.any? %>
          <p>Categories: <%= render @post.categories %></p>
        <% end %>
      </div>
      <hr/>
      <% if user_signed_in? %>
      <%= link_to "Edit", edit_post_path(@post), class: "btn btn-success btn-round" %>
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "btn btn-danger btn-round" %>
      <% end %>
    </div>
    <div class="col-xs-3" id="sb-categories">
      <%= render 'categories/categories', obj: @categories %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-1">
      <%= render 'disqus' %>
    </div>
  </div>
</div>
<script>
$(document).ready(function() {
  $(".post-content img").addClass("img-responsive");
});
</script>