config/routes.rb
Rails.application.routes.draw do
  resources :categories #, only: [:create, :show, :edit, :destroy]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :posts
  resources :contacts, only: [:new, :create]
  resources :galleries

  resources :tasks do
    member do
      put :change
    end
  end

  root "pages#home"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
    # @categories = Category.all
  end

  def show
    if current_user
      @category_posts = @category.posts.paginate(page: params[:page], per_page: 5)
    else
      @category_posts = @category.posts.where(publish: true).paginate(page: params[:page], per_page: 5)
    end
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category name was update!"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def destroy
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_categories.html.erb
<h3>Categories</h3>
<ul class="list-group">
<% obj.each do |category| %>
  <li class="list-group-item">
    <p><strong><%= link_to "#{category.name}", category_path(category) %><strong</p>
  </li>
<% end %>
</ul>

app/views/categories/_category.html.erb
<span class="label label-primary"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
<% end %>
<div class="col-xs-offset-4 col-xs-4">
  [<%= link_to "Cancel Request", posts_path %>]
</div>

app/views/categories/edit.html.erb
<h1 class="text-center">Edit Category Name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center">All Categories</h1>
<div class="container text-center">
  <%= will_paginate %>
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <ul class="list-group">
      <% @categories.each do |category| %>
        <li class="list-group-item">
          <p><strong><%= link_to "#{category.name}", category_path(category) %><strong</p>
        </li>
      <% end %>
    </ul>
    </div>
  </div>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center">Create New Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= "Category: #{@category.name}" %></h1>
    <% if user_signed_in? %>
    <%= link_to "Edit Category Name", edit_category_path(@category), class: "btn btn-success btn-xs" %>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-9">
      <div class="text-center"><%= will_paginate @category_posts %></div>
        <%= render 'posts/post', obj: @category_posts %>
      <div class="text-center"><%= will_paginate @category_posts %></div>
    </div>
    <div class="col-xs-3">
      <%= render 'categories/categories', obj: @categories %>
    </div>
  </div>
</div>