config/routes.rb
Rails.application.routes.draw do
  resources :categories #, only: [:create, :show, :edit, :destroy]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :posts
  resources :contacts, only: [:new, :create]
  resources :galleries

  resources :tasks do
    member do
      put :change
    end
  end

  root "pages#home"
end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Get Shit Done Kit by Creative Tim</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' %>

    <%= stylesheet_link_tag '//cdn.rawgit.com/konpa/devicon/master/devicon.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//google-code-prettify.googlecode.com/svn/loader/run_prettify.js" %>

    <%= yield :style %>
  </head>
  <body data-features="<%= yield :features %>" class="<%= yield :class %>">

    <%= yield %>

  </body>
</html>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col col-xs-12 text-center">
        <p>&copy; 2017 James Garcia - All Rights Reserved</p>
      </div>
    </div>
    <% if user_signed_in? %>
      <%= link_to('logout', destroy_user_session_path, method: :delete) %>
    <% else %>
      <%= link_to('login', new_user_session_path) %>
    <% end %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "GJ", root_path, class: "navbar-brand1 my-logo" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", root_path(anchor: "about") %></li>
        <li><%= link_to "Portfolio", root_path(anchor: "portfolio") %></li>
        <li><%= link_to "Skills", root_path(anchor: "skills") %></li>
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_messages.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garcia James</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/messages" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>